In [1]:
import pandas as pd
import numpy as np

In [66]:
df=pd.read_csv("C:\\Users\\eiti mittal\\Downloads\\processed.cleveland (2).data")

In [67]:
df.head()

63.0  1.0  1.0.1  145.0  233.0  1.0.2  2.0  150.0  0.0  2.3  3.0 0.0.1  \
0  67.0  1.0    4.0  160.0  286.0    0.0  2.0  108.0  1.0  1.5  2.0   3.0   
1  67.0  1.0    4.0  120.0  229.0    0.0  2.0  129.0  1.0  2.6  2.0   2.0   
2  37.0  1.0    3.0  130.0  250.0    0.0  0.0  187.0  0.0  3.5  3.0   0.0   
3  41.0  0.0    2.0  130.0  204.0    0.0  2.0  172.0  0.0  1.4  1.0   0.0   
4  56.0  1.0    2.0  120.0  236.0    0.0  0.0  178.0  0.0  0.8  1.0   0.0   

   6.0  0  
0  3.0  2  
1  7.0  1  
2  3.0  0  
3  3.0  0  
4  3.0  0

In [68]:
title=["age","sex","cp","restbp","chol","fbs","restecg","thalach",
"exang","oldpeak","slope","ca","thal","hd"]

In [70]:
df.head()

age  sex   cp  restbp   chol  fbs  restecg  thalach  exang  oldpeak  \
0  67.0  1.0  4.0   160.0  286.0  0.0      2.0    108.0    1.0      1.5   
1  67.0  1.0  4.0   120.0  229.0  0.0      2.0    129.0    1.0      2.6   
2  37.0  1.0  3.0   130.0  250.0  0.0      0.0    187.0    0.0      3.5   
3  41.0  0.0  2.0   130.0  204.0  0.0      2.0    172.0    0.0      1.4   
4  56.0  1.0  2.0   120.0  236.0  0.0      0.0    178.0    0.0      0.8   

   slope   ca thal  hd  
0    2.0  3.0  3.0   2  
1    2.0  2.0  7.0   1  
2    3.0  0.0  3.0   0  
3    1.0  0.0  3.0   0  
4    1.0  0.0  3.0   0

In [71]:
df.isnull()

age    sex     cp  restbp   chol    fbs  restecg  thalach  exang  \
0    False  False  False   False  False  False    False    False  False   
1    False  False  False   False  False  False    False    False  False   
2    False  False  False   False  False  False    False    False  False   
3    False  False  False   False  False  False    False    False  False   
4    False  False  False   False  False  False    False    False  False   
..     ...    ...    ...     ...    ...    ...      ...      ...    ...   
297  False  False  False   False  False  False    False    False  False   
298  False  False  False   False  False  False    False    False  False   
299  False  False  False   False  False  False    False    False  False   
300  False  False  False   False  False  False    False    False  False   
301  False  False  False   False  False  False    False    False  False   

     oldpeak  slope     ca   thal     hd  
0      False  False  False  False  False  
1      False  False  False  False  False  
2      False  False  False  False  False  
3      False  False  False  False  False  
4      False  False  False  False  False  
..       ...    ...    ...    ...    ...  
297    False  False  False  False  False  
298    False  False  False  False  False  
299    False  False  False  False  False  
300    False  False  False  False  False  
301    False  False  False  False  False  

[302 rows x 14 columns]

In [72]:
df.isnull().any()

age        False
sex        False
cp         False
restbp     False
chol       False
fbs        False
restecg    False
thalach    False
exang      False
oldpeak    False
slope      False
ca         False
thal       False
hd         False
dtype: bool

In [73]:
df['age'].unique()

array([67., 37., 41., 56., 62., 57., 63., 53., 44., 52., 48., 54., 49.,
       64., 58., 60., 50., 66., 43., 40., 69., 59., 42., 55., 61., 65.,
       71., 51., 46., 45., 39., 68., 47., 34., 35., 29., 70., 77., 38.,
       74., 76.])

In [74]:
df['cp'].unique()


array([4., 3., 2., 1.])

In [75]:
df['sex'].unique()


array([1., 0.])

In [76]:
df['restbp'].unique()


array([160., 120., 130., 140., 172., 150., 110., 132., 117., 135., 112.,
       105., 124., 125., 142., 128., 145., 170., 155., 104., 180., 138.,
       108., 134., 122., 115., 118., 100., 200.,  94., 165., 102., 152.,
       101., 126., 174., 148., 178., 158., 192., 129., 144., 123., 136.,
       146., 106., 156., 154., 114., 164.])

In [77]:
df['chol'].unique()


array([286., 229., 250., 204., 236., 268., 354., 254., 203., 192., 294.,
       256., 263., 199., 168., 239., 275., 266., 211., 283., 284., 224.,
       206., 219., 340., 226., 247., 167., 230., 335., 234., 233., 177.,
       276., 353., 243., 225., 302., 212., 330., 175., 417., 197., 198.,
       290., 253., 172., 273., 213., 305., 216., 304., 188., 282., 185.,
       232., 326., 231., 269., 267., 248., 360., 258., 308., 245., 270.,
       208., 264., 321., 274., 325., 235., 257., 164., 141., 252., 255.,
       201., 222., 260., 182., 303., 265., 309., 307., 249., 186., 341.,
       183., 407., 217., 288., 220., 209., 227., 261., 174., 281., 221.,
       205., 240., 289., 318., 298., 564., 246., 322., 299., 300., 293.,
       277., 214., 207., 223., 160., 394., 184., 315., 409., 244., 195.,
       196., 126., 313., 259., 200., 262., 215., 228., 193., 271., 210.,
       327., 149., 295., 306., 178., 237., 218., 242., 319., 166., 180.,
       311., 278., 342., 169., 187., 157., 176., 24

In [78]:
df['fbs'].unique()


array([0., 1.])

In [79]:
df['restecg'].unique()



array([2., 0., 1.])

In [80]:
df['thalach'].unique()


array([108., 129., 187., 172., 178., 160., 163., 147., 155., 148., 153.,
       142., 173., 162., 174., 168., 139., 171., 144., 132., 158., 114.,
       151., 161., 179., 120., 112., 137., 157., 169., 165., 123., 128.,
       152., 140., 188., 109., 125., 131., 170., 113.,  99., 177., 141.,
       180., 111., 143., 182., 150., 156., 115., 149., 145., 146., 175.,
       186., 185., 159., 130., 190., 136.,  97., 127., 154., 133., 126.,
       202., 103., 166., 164., 184., 124., 122.,  96., 138.,  88., 105.,
       194., 195., 106., 167.,  95., 192., 117., 121., 116.,  71., 118.,
       181., 134.,  90.])

In [81]:
df['exang'].unique()


array([1., 0.])

In [82]:
df['oldpeak'].unique()


array([1.5, 2.6, 3.5, 1.4, 0.8, 3.6, 0.6, 3.1, 0.4, 1.3, 0. , 0.5, 1.6,
       1. , 1.2, 0.2, 1.8, 3.2, 2.4, 2. , 2.5, 2.2, 2.8, 3. , 3.4, 6.2,
       4. , 5.6, 2.9, 0.1, 2.1, 1.9, 4.2, 0.9, 1.1, 3.8, 0.7, 0.3, 2.3,
       4.4])

In [83]:
df['slope'].unique()


array([2., 3., 1.])

In [84]:
df['ca'].unique()


array(['3.0', '2.0', '0.0', '1.0', '?'], dtype=object)

In [85]:
df['thal'].unique()


array(['3.0', '7.0', '6.0', '?'], dtype=object)

In [86]:
df['hd'].unique()

array([2, 1, 0, 3, 4], dtype=int64)

In [87]:
l1=(df['ca']=='?')
l2=(df['thal']=='?')
print(len(df.loc[l1]))
print(len(df.loc[l2]))

4
2


In [88]:
l1=((df['ca']!='?').mean())
print(l1)

0.9867549668874173


In [89]:
l1=((df['ca']!='?').mean()).round()
df['ca'].replace('?',l1,inplace=True)
df['ca'].unique()

array(['3.0', '2.0', '0.0', '1.0', 1.0], dtype=object)

In [90]:
L1=str(l1)
df['ca'].replace(1.0,L1,inplace=True)
df['ca'].unique()

array(['3.0', '2.0', '0.0', '1.0'], dtype=object)

In [91]:
l2=((df['thal']!='?').mean()).round()
l2=str(l2)
df['thal'].replace('?',l2,inplace=True)
df['thal'].unique()

array(['3.0', '7.0', '6.0', '1.0'], dtype=object)